export enum quotesActionsTypes {
    QUOTES_LOADING = 'Quotes_Loading',
    QUOTES_SUCCESS = 'Quotes_Success',
    QUOTES_FAILED = 'Quotes_Failed',
    // POST_QUOTE = 'Post_Quote',

    LIKE_QUOTE_REQ = 'LIKE_QUOTE_REQ',
    LIKE_QUOTES_SUCCESS = 'LIKE_QUOTES_SUCCESS',
    LIKE_QUOTES_FAILED = 'LIKE_QUOTES_FAILED',

    UNLIKE_QUOTE_REQ = 'UNLIKE_QUOTE_REQ',
    UNLIKE_QUOTES_SUCCESS = 'UNLIKE_QUOTES_SUCCESS',
    UNLIKE_QUOTES_FAILED = 'UNLIKE_QUOTES_FAILED'
}